### ISSUE TITLE
cuda溢出

### ISSUE THREAD

**Issue by passermyh** [zjukg/AnKGE#2]
![QQ截图20230418232953](https://user-images.githubusercontent.com/71198047/232827178-0a9cfa11-72bc-47de-b244-d0b8bc476f46.png)
您好，非常感谢您的工作。
我在复现您的代码的时候，使用hake作为base时，我将batchsize已经调整到非常小了，但还是报了溢出的错误，请问哪里还能尽可能不影响结果的改动呢？（12G）

**Comment by Modberge** [comment]
这里显存溢出的原因是在计算得分函数的kNN最近邻时，我们会将所有实体\关系作为候选计算其得分并进行排序，你可以尝试降低EVAL_BS的值来减小批次大小，这样改动理论上不会对模型效果产生影响，但是需要注意的是，这会极大延长kNN检索时间和模型的测试时间。
