### ISSUE TITLE
缺失pickle文件的问题

### ISSUE THREAD

**Issue by RRRRRusellllll** [zjukg/AnKGE#4]
您好！非常感激您在知识图谱的贡献以及开源代码方便后续的复现和研究工作，我在复现您的代码时遇到了问题，具体的问题是，当我运行完sh scripts/FreeBase/TransE_Rev_FB.sh后期望继续运行sh scripts/FreeBase/AnKnn_TransE_FB.sh，但是系统报错为：/code/AnKGE/output/kNN_candidate/FB15K237/TransE/1_1_3_1000_40_kNN.pickle，请问针对这个问题应该如何解决呢

非常感谢！

**Comment by RRRRRusellllll** [comment]
我现在的做法是，如果更改了配置文件中的这些变量1_1_3_1000_40，就把那个如果有该文件就使用的代码注释，然后手动添加一个这个文件；如果不改变了就不把代码注释，就不用每次都找KNN了，不知道这么做可不可以。

**Comment by Modberge** [comment]
你好，首先非常抱歉，最近时间在准备毕业设计没有及时回复。

文件 “/code/AnKGE/output/kNN_candidate/FB15K237/TransE/1_1_3_1000_40_kNN.pickle” 是AnKGE模型执行kNN检索的缓存文件，在第一次按照相应参数运行时会进行类比元素检索，如果注释掉这个文件相关代码会导致后续代码无法正常运行，所以建议不要进行注释，如果您尚未解决这个问题，我建议您贴出完整的异常栈，这样可以进一步分析哪一步出了问题。

**Comment by qixiaonan12** [comment]
> 我现在的做法是，如果更改了配置文件中的这些变量1_1_3_1000_40，就把那个如果有该文件就使用的代码注释，然后手动添加一个这个文件；如果不改变了就不把代码注释，就不用每次都找KNN了，不知道这么做可不可以。

您好，请问这个问题解决了吗？希望收到您的回复与您交流。
